Repository sp15-team7/wadam, pull requests merged in 2025-06, with the labels that each got.

#12 Auth.js 기반 인증 시스템 구현
  .gitignore
  package.json
  pnpm-lock.yaml
  prettier.config.mjs
  public/icons/ui/icon-burst.svg
  public/icons/ui/icon-default-user.svg
  public/logos/logo-ivory-lg.png
  public/logos/logo-ivory-sm.png
  public/logos/logo-red-lg.png
  public/logos/logo-red-sm.png
  src/app/(routes)/myprofile/page.tsx
  src/app/(routes)/page.tsx
  src/app/(routes)/signin/page.tsx
  src/app/(routes)/signup/page.tsx
  src/app/api/auth/[...nextauth]/routes.ts
  src/app/globals.css
  src/app/layout.tsx
  src/feature/auth/README.md
  src/feature/auth/actions/auth.action.ts
  src/feature/auth/components/SignInForm.tsx
  src/feature/auth/components/SignUpForm.tsx
  src/feature/auth/constants/auth.message.ts
  src/feature/auth/constants/dummy
  src/feature/auth/hooks/dummy
  src/feature/auth/hooks/useAuthSession.ts
  src/feature/auth/index.ts
  src/feature/auth/libs/auth.config.ts
  src/feature/auth/libs/auth.ts
  src/feature/auth/schema/auth.schema.ts
  src/feature/auth/services/auth.service.ts
  src/feature/auth/types/auth.d.ts
  src/feature/auth/types/auth.types.ts
  src/feature/auth/utils/callbacks.utils.ts
  src/feature/auth/utils/dummy
  src/feature/auth/utils/jwt.utils.ts
  src/feature/auth/utils/providers.utils.ts
  src/middleware.ts
  src/shared/components/common/dummy
  src/shared/components/common/layouts/Header.tsx
  src/shared/components/common/layouts/HeaderLogo.tsx
  src/shared/components/layouts/Header.tsx
  src/shared/hooks/dummy
  src/shared/hooks/useDeviceSize.ts
  src/shared/libs/api/apiClient.ts
  tsconfig.json
Labels: ✨ feature

#22 Git Hooks 자동화 시스템 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .husky/commit-msg
  .husky/pre-commit
  .vscode/settings.json
  commitlint.config.mjs
  lint-staged.config.mjs
  package.json
  src/app/layout.tsx
  src/shared/components/ui/input.tsx
Labels: ✨ feature

#7 Feat/loading UI
  src/app/(routes)/page.tsx
  src/app/loading.tsx
  src/shared/components/common/skeleton-card/index.tsx
  src/shared/components/common/spinner/index.tsx
  src/shared/components/ui/Skeleton.tsx
Labels: ✨ feature

#49 Refactor/auth logo error style - qa 피드백 적용
  src/app/(entry)/signup/page.tsx
  src/feature/auth/components/FormField.tsx
  src/feature/auth/components/SignUpForm.tsx
Labels: 🔧 refactor, 🎨 design

#60 chore: coderabbit yaml 파일 정의
  .coderabbit.yaml
Labels: 🧹 chore

#64 Feat/sprint1 components responsive
  lint-staged.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/(entry)/page.tsx
  src/shared/components/common/skeleton-card/index.tsx
  src/shared/components/common/star-rating/index.tsx
  src/shared/components/common/user-avatar/index.tsx
Labels: ✨ feature, 🔧 refactor

#55 feat: 로그인 페이지 스타일 및 UI 개선
  lint-staged.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/icons/ui/icon-kakao.svg
  src/app/(entry)/signin/page.tsx
  src/app/(entry)/signup/page.tsx
  src/feature/auth/components/ErrorMessage.tsx
  src/feature/auth/components/FormField.tsx
  src/feature/auth/components/SignInForm.tsx
  src/feature/auth/components/SignUpForm.tsx
  src/shared/hooks/useToggle.ts
  src/shared/libs/getComponentFromChildren.ts
Labels: 🎨 design

#68 Feat/carousel component
  package.json
  pnpm-lock.yaml
  src/app/(main)/wines/page.tsx
  src/feature/wines/components/MonthlyWineSection.tsx
  src/shared/components/common/skeleton-card/index.tsx
  src/shared/components/ui/Carousel.tsx
Labels: ✨ feature

#69 공통 컴포넌트 개발 (progress, custom slider, autoLayout Button)
  package.json
  pnpm-lock.yaml
  src/feature/reviews/components/wine-taste-slider/index.tsx
  src/feature/wines/components/dummy
  src/feature/wines/components/wine-flavors/index.tsx
  src/feature/wines/components/wine-price-slider/index.tsx
  src/feature/wines/components/wine-progress/index.tsx
  src/feature/wines/components/wine-types/index.tsx
  src/feature/wines/types/flavor-label.ts
  src/feature/wines/types/wine-taste.ts
  src/shared/components/ui/dual-range-slider.tsx
  src/shared/components/ui/progress.tsx
  src/shared/components/ui/slider.tsx
Labels: ✨ feature

#84 Feat/sprint2 qa resolve
  src/app/(main)/wines/page.tsx
  src/feature/wines/components/MonthlyWineSection.tsx
  src/shared/components/common/modal/Modal.tsx
  src/shared/components/common/modal/ModalCloseButton.tsx
  src/shared/components/common/modal/ModalTitle.tsx
  src/shared/components/common/skeleton-card/index.tsx
  src/shared/components/common/star-rating/index.tsx
  src/shared/components/ui/carousel.tsx
  src/shared/components/ui/skeleton.tsx
  src/shared/stores/useModalStore.ts
Labels: ✨ feature, 🔧 refactor

#78 style: qa - 스타일 수정
  src/feature/reviews/components/wine-taste-slider/index.tsx
  src/feature/wines/components/wine-flavors/index.tsx
  src/feature/wines/components/wine-types/index.tsx
Labels: 🎨 design

#92 Feat/global inner component
  src/app/(main)/wines/page.tsx
  src/feature/wines/components/MonthlyWineSection.tsx
  src/feature/wines/components/card/DetailCard.tsx
  src/shared/components/container/InnerContainer.tsx
Labels: ✨ feature

#99 Fix: 인증 관련 페이지 및 레이아웃 수정
  src/app/(entry)/signin/page.tsx
  src/app/(entry)/signup/page.tsx
  src/feature/auth/components/AuthLink.tsx
  src/feature/auth/components/ErrorMessage.tsx
  src/feature/auth/components/FormField.tsx
  src/feature/auth/components/SignInForm.tsx
  src/feature/auth/components/SignUpForm.tsx
  src/feature/auth/schema/auth.schema.ts
  src/shared/components/ui/button.tsx
Labels: 🎨 design

#112 Feat/wine aroma card
  public/icons/ui/icon-aroma-apple.png
  public/icons/ui/icon-aroma-baking.png
  public/icons/ui/icon-aroma-berry.png
  public/icons/ui/icon-aroma-caramel.png
  public/icons/ui/icon-aroma-cherry.png
  public/icons/ui/icon-aroma-chocolate.png
  public/icons/ui/icon-aroma-citrus.png
  public/icons/ui/icon-aroma-default.png
  public/icons/ui/icon-aroma-earth.png
  public/icons/ui/icon-aroma-flower.png
  public/icons/ui/icon-aroma-grass.png
  public/icons/ui/icon-aroma-leather.png
  public/icons/ui/icon-aroma-mineral.png
  public/icons/ui/icon-aroma-oak.png
  public/icons/ui/icon-aroma-peach.png
  public/icons/ui/icon-aroma-pepper.png
  public/icons/ui/icon-aroma-spice.png
  public/icons/ui/icon-aroma-tobacco.png
  public/icons/ui/icon-aroma-tropical.png
  public/icons/ui/icon-aroma-vanilla.png
  src/app/(main)/wines/[wineid]/page.tsx
  src/feature/reviews/components/review-form/ReviewFormButton.tsx
  src/feature/wines/components/wine-progress/index.tsx
  src/feature/wines/detail/components/WineAromaCard.tsx
  src/feature/wines/detail/components/WineAromaCards.tsx
  src/feature/wines/detail/components/WineDetailCardSection.tsx
  src/feature/wines/detail/components/WineDetailReviewList.tsx
  src/feature/wines/detail/components/WineDetailTitle.tsx
  src/feature/wines/detail/components/WineFlavorProfileSection.tsx
  src/feature/wines/hooks/useWineDetailsQuery.ts
  src/shared/libs/api/apiClient.ts
Labels: ✨ feature

#118 Feat/wine detail page UI ux refinement
  public/icons/ui/icon-error.png
  src/app/(main)/wines/[wineid]/page.tsx
  src/feature/reviews/components/review-form/ReviewFormButton.tsx
  src/feature/reviews/components/wine-taste-slider/index.tsx
  src/feature/wines/components/card/DetailCard.tsx
  src/feature/wines/components/card/MonthlyCard.tsx
  src/feature/wines/components/wine-progress/index.tsx
  src/feature/wines/detail/components/WineAromaCard.tsx
  src/feature/wines/detail/components/WineAromaCards.tsx
  src/feature/wines/detail/components/WineDetailCardSection.tsx
  src/feature/wines/detail/components/WineDetailReviewList.tsx
  src/feature/wines/detail/components/WineDetailTitle.tsx
  src/feature/wines/detail/components/WineFlavorProfileSection.tsx
  src/feature/wines/hooks/useWineDetailsQuery.ts
  src/feature/wines/schema/wine.schema.ts
  src/feature/wines/utils/dummy
  src/feature/wines/utils/shuffleArray.ts
  src/shared/components/common/error-display/index.tsx
  src/shared/components/common/skeleton-card/index.tsx
Labels: ✨ feature

#119 마이페이지 - 내가 작성한 리뷰 수정 기능 로직 추가 (1차 merge)
  src/feature/libs/api/userApi.ts
  src/feature/myprofile/components/ReviewCardList.tsx
  src/feature/reviews/components/review-form/EditReviewForm.tsx
  src/feature/reviews/components/review-form/ReviewFormButton.tsx
  src/feature/reviews/schemas/reviews.schema.ts
  src/feature/wines/components/button/CardDropdownMenu.tsx
  src/feature/wines/components/card/MyReviewCard.tsx
  src/feature/wines/components/wine-flavors/index.tsx
  src/shared/components/common/modal/Modal.tsx
  src/shared/components/common/modal/ModalCloseButton.tsx
Labels: ✨ feature, 🔧 refactor

#122 마이페이지 리뷰 수정/삭제, 와인 수정/삭제 구현
  src/feature/libs/api/userApi.ts
  src/feature/myprofile/components/ReviewCardList.tsx
  src/feature/myprofile/components/WineCardList.tsx
  src/feature/reviews/components/review-form/EditReviewForm.tsx
  src/feature/reviews/components/wine-review-form/EditWineReviewForm.tsx
  src/feature/reviews/schemas/reviews.schema.ts
  src/feature/wines/components/card/DetailCard.tsx
  src/feature/wines/components/card/MyReviewCard.tsx
  src/feature/wines/schema/wine.schema.ts
  src/feature/wines/services/wine.service.ts
Labels: ✨ feature, 🔧 refactor

#121 Feat/wine registration modal component
  src/feature/wines/components/modal/WineRegistrationModal.tsx
  src/feature/wines/components/wine-price-slider/index.tsx
  src/feature/wines/schema/wine.schema.ts
  src/feature/wines/types/wine.types.ts
  src/shared/components/common/modal/Modal.tsx
  src/shared/components/ui/dropdown-menu.tsx
Labels: ✨ feature

#126 와인 상세 페이지 수정 및 삭제 로직 연결
  src/app/card/page.tsx
  src/feature/myprofile/components/ReviewCardList.tsx
  src/feature/myprofile/components/WineCardList.tsx
  src/feature/reviews/components/review-form/EditReviewForm.tsx
  src/feature/reviews/components/review-form/ReviewFormButton.tsx
  src/feature/reviews/hooks/useLikeReviewMutation.ts
  src/feature/wines/components/card/ReviewCard.tsx
  src/feature/wines/detail/components/WineDetailReviewList.tsx
Labels: 🔧 refactor

#128 Fix/missing features
  src/app/(main)/wines/[wineid]/page.tsx
  src/feature/reviews/components/wine-taste-slider/index.tsx
  src/feature/wines/components/card/DetailCard.tsx
  src/feature/wines/components/card/MonthlyCard.tsx
  src/feature/wines/components/card/WineCard.tsx
  src/feature/wines/components/wine-progress/index.tsx
  src/feature/wines/detail/components/WineDetailCardSection.tsx
  src/feature/wines/detail/components/WineDetailReviewList.tsx
  src/feature/wines/detail/components/WineFlavorProfileSection.tsx
  src/feature/wines/hooks/useUserWinesQuery.ts
  src/feature/wines/schema/wine.schema.ts
  src/shared/components/common/modal/Modal.tsx
  src/shared/components/common/star-rating/index.tsx
Labels: ✨ feature, 🔧 refactor

#133 sprint3 qa - 수정 사항
  src/feature/libs/api/userApi.ts
  src/feature/myprofile/components/ProfileCard.tsx
  src/feature/myprofile/components/WineCardList.tsx
  src/feature/reviews/components/review-form/ReviewFormButton.tsx
  src/feature/wines/components/wine-flavors/index.tsx
  src/shared/components/common/modal/Modal.tsx
Labels: 🐞 bug, 🔧 refactor, 🎨 design

#140 Refactor/landing UI changes
  src/feature/landing/components/FilterMyWineSection.tsx
  src/feature/landing/components/Hero.tsx
  src/feature/landing/components/TodayWineSection.tsx
  src/feature/landing/components/WineReviewSection.tsx
  src/feature/landing/constants/styles.ts
  src/feature/myprofile/components/MyPage.tsx
  src/feature/myprofile/components/ProfileCard.tsx
  src/feature/myprofile/components/ReviewCardList.tsx
  src/feature/wines/components/card/DetailCard.tsx
  src/feature/wines/components/card/MyReviewCard.tsx
Labels: ✨ feature, 🔧 refactor

#141 Refactor/landing UI changes
  src/feature/landing/components/FilterMyWineSection.tsx
  src/feature/landing/components/Hero.tsx
  src/feature/landing/components/TodayWineSection.tsx
  src/feature/landing/components/WineReviewSection.tsx
  src/feature/landing/constants/styles.ts
  src/feature/myprofile/components/MyPage.tsx
  src/feature/myprofile/components/ProfileCard.tsx
  src/feature/myprofile/components/ReviewCardList.tsx
  src/feature/wines/components/card/DetailCard.tsx
  src/feature/wines/components/card/MyReviewCard.tsx
Labels: ✨ feature, 🔧 refactor
